version: "3"

services:
  nginx:
    container_name: nginx_statping
    build:
      context: .
    ports:
    - "8080:80"
    environment:
      - STATPING_SERVER="http://statping:8080/"
    links:
      - statping

  statping:
    container_name: statping
    image: statping/statping
    volumes:
      - statping_data:/app
    environment:
      DB_CONN: sqlite
    ports:
    - "8081:8080"

volumes:
  statping_data:
